[package]
name = "backuper-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
backuper-core = { path = "../backuper-core" }
tokio = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
tokio-cron-scheduler = { workspace = true }
tar = { workspace = true }
zstd = { workspace = true }
russh = { workspace = true }
russh-sftp = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
